name: Aprendiengo Github Actions en Platzi
run-name: Aprendiending
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Nodejs init
        uses: actions/setup-node@v3
      - name: Correr script
        run: node index.js